name: app
description: A new Flutter project.
publish_to: 'none'
version: 2.0.5+3

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  assets_audio_player: ^3.0.5
  wakelock: ^0.6.1+2
  scrollable_positioned_list: ^0.3.2
  syncfusion_flutter_gauges: ^20.2.36
  flutter_slidable: ^2.0.0
  focused_menu: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_native_splash: ^2.2.4

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/alarm.mp3
    - assets/stretchings/
    - assets/stretchings/karate/
    - assets/stretchings/karate/stretches/
    - assets/splash.png